// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_Team0303.Models;

namespace Mission08_Team0303.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission08_Team0303.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Category = "Home",
                            Completed = false,
                            DueDate = "Tuesday",
                            Quadrant = 4,
                            task = "Do laundry"
                        },
                        new
                        {
                            TaskId = 2,
                            Category = "Church",
                            Completed = false,
                            DueDate = "Sunday",
                            Quadrant = 2,
                            task = "Write talk"
                        },
                        new
                        {
                            TaskId = 3,
                            Category = "Work",
                            Completed = true,
                            Quadrant = 1,
                            task = "Go to work"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
